# File per eventi manuali
# Inteso per eventi da posti che non hanno un sito web
# Formato date: array di "DD-MM-YYYY" per TimeFrame::Dates,
# "DD-MM-YYYY/DD-MM-YYYY" per TimeFrame::Period
# La categoria dovrebbe essere plurale (e.g., "Mercatini" anzich√© "Mercatino")

# Esempi:
#
# [[events]]
# title = "Mercatino di Natale"
# date = "21-12-2025/06-01-2026"
# category = "Mercatini"
# locations = [
#   { name = "Cavana", url = "https://link.to/event" },
#   { name = "Ponterosso", url = "https://link.to/other/event" },
# ]
#
# [[events]]
# title = "Concerto di Natale"
# date = ["21-12-2025", "23-12-2025"]
# category = "Concerti"
# locations = [
#   { name = "Cavana", url = "https://link.to/event" },
# ]
